title: GrowPoder
description: Learn how to grow and earn money with faceless content, YouTube Shorts, and AI tools.
baseurl: ""
url: "https://ditu87.github.io/growpoder" # Replace with your GitHub username
theme: minima
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /blog/:title/
markdown: kramdown
